### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by yxyyyt** [yxyyyt/hummer#1]
- [ ] namenode dn and filename cache thread safe
- [ ] DataNode execute replicate command using more thread
- [ ] client high availability
- [ ] client upload、download using more thread testcase
- [ ] Manual trigger rebalance
- [ ] schedule auto trigger rebalance
- [ ] schedule thread manager
- [ ] rpc service Business logic decoupling
- [ ] server extension，spi supported
- [ ] random allocate DataNode，prevent hot data 
- [ ] upload file fail，delete file metadata
- [ ] file add version，prevent old version replace new version
- [ ] increment 、full report must exist meta data，or else distribute remove command
- [ ] schedule inflight commands repeat distribute while timeout
